CXX = g++
MAKE = make
AR = ar
CXXFLAGS = -I./lib/ -L./lib/ -luniDQP -Wall -g 
OPTIONS = -D__STDC_FORMAT_MACROS

#Network parameters
OPTIONS += 	-DNSERVERS=39 
OPTIONS += 	-DPORT=19999
OPTIONS += 	-DHOST='"10.20.12.170"' 

#Experiments parameters
OPTIONS += 	-DALPHA=0.03f
OPTIONS += 	-DCACHESIZE=100000

#others parameters
OPTIONS += 	-DDATAFILE='"/scratch/youngmoon01/garbage2.bin"'
OPTIONS += 	-DLOT=1024
