CXX = g++
MAKE = make
AR = ar
CXXFLAGS = -I./lib/ -L./lib/ -luniDQP -Wall -g 
OPTIONS = -D__STDC_FORMAT_MACROS

#Experiments parameters
OPTIONS += 	-DALPHA=0.03f
OPTIONS += 	-DCACHESIZE=100000

#others parameters
OPTIONS += 	-DLOT=1024
