CXXFLAGS = -I../lib/ -L../lib/ -lgtest -luniDQP -lpthread -g 

LRU:
	c++ LRUcacheTEST.cpp $(CXXFLAGS) 

SET:
	c++ SETcacheTEST.cpp $(CXXFLAGS) 

toDouble:
	c++ toDoubleTEST.cpp $(CXXFLAGS) 

toArray:
	c++ toArrayTEST.cpp $(CXXFLAGS) 
